# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: step_label_plugin
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    - flatland-fork
    - microdrop >=2.4
    - microdrop-plugin-manager >=0.11
    - path_helpers >=0.2.post3

  run:
    - flatland-fork
    - microdrop >=2.4
    - microdrop-plugin-manager >=0.11
    - path_helpers >=0.2.post3

about:
  home: http://github.com/wheeler-microfluidics/step_label_plugin
  license: BSD
